# Generated by Django 5.1.2 on 2024-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bears',
            name='performers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bears',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bears',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
