# Generated by Django 5.1.2 on 2024-10-28 15:02

import scraper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_bears_performers_alter_bears_image_alter_bears_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sengoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=scraper.models.get_image_upload_sengoku)),
            ],
        ),
        migrations.AlterField(
            model_name='bears',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=scraper.models.get_image_upload_bears),
        ),
    ]
