# Generated by Django 5.1.2 on 2024-10-29 14:01

import scraper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_sengoku_alter_bears_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helluva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=scraper.models.get_image_upload_sengoku)),
            ],
        ),
        migrations.AlterField(
            model_name='sengoku',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=scraper.models.get_image_upload_sengoku),
        ),
    ]
