# Generated by Django 5.1.2 on 2024-10-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_fuzz_alter_helluva_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuzz',
            name='performers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
