# Generated by Django 5.1.2 on 2025-07-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_hardrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tora',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
